steps:
#
# Copy from src to dist
#
- name: 'python:3-slim'
  dir: quickstart
  args:
  - 'bash'
  - '-c'
  - |
    pip install pipenv
    pipenv install
    pipenv run ./dist.py
  env:
  - 'PYTHONUNBUFFERED=1'
  - 'TAG_NAME=$TAG_NAME'
  - 'BRANCH_NAME=$BRANCH_NAME'

#
# Copy from dist to bucket
#
artifacts:
  objects:
    location: 'gs://$_QUICKSTART_BUCKET_NAME'
    paths: ['quickstart/_dist/*.zip']
