name: Build Test Publish

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build-test-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: Build artifacts
      uses: ./.github/actions/build_artifacts

    # Docker actions run as root, fix ownership of _dist
    - name: Fix owner
      run: |
        sudo chown -R `id -u`:`id -g` ./quickstart/_dist

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v1
      with:
        name: test-artifacts
        path: ./quickstart/_dist

  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        starter: ["multi-cloud", "aks", "eks", "gke"]

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1

    - name: 'Docker login'
      run: |
        echo ${{ secrets.DOCKER_AUTH }} | docker login --username kbstci --password-stdin

    - name: Build ${{ matrix.starter }} image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker run \
          --rm \
          --privileged \
          -v `pwd`/oci:/tmp/work \
          -v $HOME/.docker:/root/.docker \
          --entrypoint buildctl-daemonless.sh \
          moby/buildkit:master \
              build \
              --frontend dockerfile.v0 \
              --local context=/tmp/work \
              --local dockerfile=/tmp/work \
              --output type=image,name=kubestack/framework-dev:test-${{ github.sha }}-${{ matrix.starter }},push=true \
              --export-cache type=registry,ref=kubestack/framework-dev:buildcache-${{ matrix.starter }},push=true \
              --import-cache type=registry,ref=kubestack/framework-dev:buildcache-${{ matrix.starter }} \
              --opt target=${{ matrix.starter }}

  test:
    runs-on: ubuntu-latest
    needs: [build-test-artifacts, build-image]
    strategy:
      matrix:
        starter: ["multi-cloud", "aks", "eks", "gke"]

    steps:
    - name: 'Download test-artifacts'
      uses: actions/download-artifact@v1
      with:
        name: test-artifacts

    - name: 'Unzip ${{ matrix.starter }} quickstart'
      run: |
        unzip test-artifacts/kubestack-starter-${{ matrix.starter }}-*.zip

    - name: 'Docker build'
      env:
        DOCKER_BUILDKIT: 1
      working-directory: ./kubestack-starter-${{ matrix.starter }}
      # retagging here is necessary because we only push images
      # to kubestack/framework after they have been tested
      # but the Dockerfiles in the artifact have the target image name
      run: |
        SOURCE_IMAGE=kubestack/framework-dev:test-${{ github.sha }}-${{ matrix.starter }}
        docker pull $SOURCE_IMAGE
        TARGET_IMAGE=$(cat Dockerfile | sed 's/FROM //')
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker build -t test-image:${{ github.sha }} .

    - name: 'Configure Kubestack'
      working-directory: ./kubestack-starter-${{ matrix.starter }}
      run: |
        # set name_prefix
        sed -i 's/name_prefix = ""/name_prefix = "test"/g' config.auto.tfvars

    - name: 'Terraform init'
      working-directory: ./kubestack-starter-${{ matrix.starter }}
      run: |
        docker run --rm \
          -v `pwd`:/infra \
          -u `id -u`:`id -g` \
          test-image:${{ github.sha }} \
          terraform init

    - name: 'Terraform workspace new ops'
      working-directory: ./kubestack-starter-${{ matrix.starter }}
      run: |
        docker run --rm \
          -v `pwd`:/infra \
          -u `id -u`:`id -g` \
          test-image:${{ github.sha }} \
          terraform workspace new ops

    - name: 'Terraform validate'
      working-directory: ./kubestack-starter-${{ matrix.starter }}
      run: |
        docker run --rm \
          -v `pwd`:/infra \
          -u `id -u`:`id -g` \
          test-image:${{ github.sha }} \
          terraform validate

  publish-image:
    runs-on: ubuntu-latest
    needs: [test]

    strategy:
      matrix:
        starter: ["multi-cloud", "aks", "eks", "gke"]

    steps:
    - name: 'Download test-artifacts'
      uses: actions/download-artifact@v1
      with:
        name: test-artifacts

    - name: 'Docker login'
      run: |
        echo ${{ secrets.DOCKER_AUTH }} | docker login --username kbstci --password-stdin

    - name: 'Docker push'
      # pull the image built for testing
      # retag it as the image specified in the artifact
      # push the new image with the new tag
      run: |
        SOURCE_IMAGE=kubestack/framework-dev:test-${{ github.sha }}-${{ matrix.starter }}
        docker pull $SOURCE_IMAGE
        TARGET_IMAGE=$(cat test-artifacts/kubestack-starter-${{ matrix.starter }}/Dockerfile | sed 's/FROM //')
        docker tag $SOURCE_IMAGE $TARGET_IMAGE
        docker push $TARGET_IMAGE

  publish-starter:
    runs-on: ubuntu-latest
    # only publish the artifacts when tests passed and images are pushed
    # because publishing the starter is what makes a release public
    needs: [test, publish-image]

    strategy:
      matrix:
        starter: ["multi-cloud", "aks", "eks", "gke"]

    steps:
    - name: 'Download test-artifacts'
      uses: actions/download-artifact@v1
      with:
        name: test-artifacts

    - name: 'Setup gcloud'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: 'Publish ${{ matrix.starter }} starter'
      run: |
        SOURCE_FILE=test-artifacts/kubestack-starter-${{ matrix.starter }}-${{ github.sha }}.zip
        TARGET_BUCKET=dev.quickstart.kubestack.com
        if [[ GITHUB_REF = refs/tags/v* ]]
        then
          VERSION=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
          SOURCE_FILE=test-artifacts/kubestack-starter-${{ matrix.starter }}-${VERSION}.zip
          TARGET_BUCKET=quickstart.kubestack.com
        fi
        gsutil -m cp $SOURCE_FILE gs://$TARGET_BUCKET
